"""add_catalog_and_roadmap_tables

Revision ID: 622dd9a82d43
Revises: d2c3e4a2e879
Create Date: 2026-09-06 16:29:58.363409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '622dd9a82d43'
down_revision: Union[str, Sequence[str], None] = 'd2c3e4a2e879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Beginner', 'Intermediate', 'Advanced', name='roadmap_difficulty').create(op.get_bind())
    op.create_table('ai_internships',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('match_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_quotes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lofi_tracks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('tagline', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('accent', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('match_tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_contacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('pic', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('contact', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_questions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmaps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('Beginner', 'Intermediate', 'Advanced', name='roadmap_difficulty', create_type=False), server_default=sa.text("'Beginner'"), nullable=False),
    sa.Column('match_tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('author', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=True),
    sa.Column('role_title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('role_emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('role_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('roadmap_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.Text(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'roadmap_id')
    )
    op.create_table('roadmap_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roadmap_id', sa.Text(), nullable=False),
    sa.Column('edge_key', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('target_key', sa.Text(), nullable=False),
    sa.Column('dashed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('animated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'edge_key', name='uq_roadmap_edge')
    )
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('roadmap_id', sa.Text(), nullable=False),
    sa.Column('node_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('x', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('y', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('title_inside', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('always_unlocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('submission', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'node_key', name='uq_roadmap_node')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.Text(), nullable=False),
    sa.Column('node_key', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('quiz_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'roadmap_id', 'node_key', name='uq_user_roadmap_submission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('roadmap_nodes')
    op.drop_table('roadmap_edges')
    op.drop_table('roadmap_activity')
    op.drop_table('user_preferences')
    op.drop_table('roadmaps')
    op.drop_table('onboarding_questions')
    op.drop_table('internship_contacts')
    op.drop_table('roles')
    op.drop_table('lofi_tracks')
    op.drop_table('hobbies')
    op.drop_table('dev_quotes')
    op.drop_table('ai_internships')
    sa.Enum('Beginner', 'Intermediate', 'Advanced', name='roadmap_difficulty').drop(op.get_bind())
    # ### end Alembic commands ###
