"""add_github_community_collab_tables

Revision ID: bfe6d884bde2
Revises: 622dd9a82d43
Create Date: 2026-09-06 16:32:15.593938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfe6d884bde2'
down_revision: Union[str, Sequence[str], None] = '622dd9a82d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'accepted', 'rejected', name='applicant_status').create(op.get_bind())
    sa.Enum('open', 'full', name='collab_status').create(op.get_bind())
    sa.Enum('text', 'anon', name='channel_kind').create(op.get_bind())
    op.create_table('direct_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_low', sa.UUID(), nullable=False),
    sa.Column('user_high', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_low < user_high', name='ck_direct_conv_user_order'),
    sa.ForeignKeyConstraint(['user_high'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_low'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low', 'user_high', name='uq_direct_conv_pair')
    )
    op.create_table('github_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('total_commits', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('public_repos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('top_languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weeks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('initial', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('is_team_community', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('banned_by', sa.UUID(), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('kind', postgresql.ENUM('text', 'anon', name='channel_kind', create_type=False), server_default=sa.text("'text'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collab_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('author_avatar', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('author_role', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('needed_roles', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('community_id', sa.Text(), nullable=True),
    sa.Column('members_current', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('members_needed', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'full', name='collab_status', create_type=False), server_default=sa.text("'open'"), nullable=False),
    sa.Column('closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['community_id'], ['servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_invites',
    sa.Column('token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('server_members',
    sa.Column('server_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'user_id', name='pk_server_members')
    )
    op.create_table('collab_applicants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'rejected', name='applicant_status', create_type=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['collab_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collab_request_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['collab_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=True),
    sa.Column('dm_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('author_avatar', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('code_language', sa.Text(), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.Text(), nullable=True),
    sa.Column('attachment_kind', sa.Text(), nullable=True),
    sa.Column('attachment_size', sa.Text(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('channel_id IS NOT NULL OR dm_id IS NOT NULL', name='ck_message_destination'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dm_id'], ['direct_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('collab_request_images')
    op.drop_table('collab_applicants')
    op.drop_table('server_members')
    op.drop_table('community_invites')
    op.drop_table('collab_requests')
    op.drop_table('channels')
    op.drop_table('servers')
    op.drop_table('github_stats')
    op.drop_table('direct_conversations')
    sa.Enum('text', 'anon', name='channel_kind').drop(op.get_bind())
    sa.Enum('open', 'full', name='collab_status').drop(op.get_bind())
    sa.Enum('pending', 'accepted', 'rejected', name='applicant_status').drop(op.get_bind())
    # ### end Alembic commands ###
