"""init_auth_profile_badges_repos

Revision ID: d2c3e4a2e879
Revises: 
Create Date: 2026-09-06 16:22:56.347042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c3e4a2e879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('common', 'rare', 'epic', 'legendary', name='badge_tier').create(op.get_bind())
    sa.Enum('student', 'faculty', name='user_role').create(op.get_bind())
    op.create_table('badges',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('icon', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('tier', postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badge_tier', create_type=False), server_default=sa.text("'common'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('student', 'faculty', name='user_role', create_type=False), server_default=sa.text("'student'"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('github_repos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('forks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('language', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('language_color', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('url', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avatar_url', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('university', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('role_title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('role_emoji', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('bio', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('location', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('github_connected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('cv_file_name', sa.Text(), nullable=True),
    sa.Column('cv_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.Text(), nullable=False),
    sa.Column('earned', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_id', name='pk_user_badges')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badges')
    op.drop_table('profiles')
    op.drop_table('github_repos')
    op.drop_table('users')
    op.drop_table('badges')
    sa.Enum('student', 'faculty', name='user_role').drop(op.get_bind())
    sa.Enum('common', 'rare', 'epic', 'legendary', name='badge_tier').drop(op.get_bind())
    # ### end Alembic commands ###
