"""seed_initial_dummy_data

Revision ID: e73a1d9c2841
Revises: bfe6d884bde2
Create Date: 2026-09-06 17:00:00.000000

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone, timedelta
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from argon2 import PasswordHasher

# revision identifiers, used by Alembic.
revision: str = 'e73a1d9c2841'
down_revision: Union[str, Sequence[str], None] = 'bfe6d884bde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ph = PasswordHasher()


def upgrade() -> None:
    now = datetime.now(timezone.utc)
    pw_faculty = ph.hash("seedfaculty123")
    pw_student = ph.hash("password123")

    # 1. ROLES
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.Text),
        sa.column('title', sa.Text),
        sa.column('emoji', sa.Text),
        sa.column('tagline', sa.Text),
        sa.column('description', sa.Text),
        sa.column('accent', sa.Text),
        sa.column('match_tags', postgresql.ARRAY(sa.Text)),
        sa.column('tech_stack', postgresql.ARRAY(sa.Text)),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(roles_table, [
        {
            'id': 'frontend-engineer',
            'title': 'Frontend Engineer',
            'emoji': '',
            'tagline': 'Building interfaces that feel alive & smooth.',
            'description': 'You love making things you can see and touch right away. Focused on interactive UI, animation, and user experience.',
            'accent': '#e5e5e5',
            'match_tags': ['web-dev', 'ui-ux', 'open-source', 'gaming'],
            'tech_stack': ['React', 'TypeScript', 'Tailwind'],
            'sort_order': 1,
        },
        {
            'id': 'backend-engineer',
            'title': 'Backend Engineer',
            'emoji': '',
            'tagline': 'The scalable engine behind the scenes.',
            'description': 'You enjoy thinking about data structures, APIs, and performance. Logic and efficiency are your playground.',
            'accent': '#e5e5e5',
            'match_tags': ['web-dev', 'competitive-programming', 'cloud-devops', 'open-source'],
            'tech_stack': ['Rust', 'Go', 'PostgreSQL'],
            'sort_order': 2,
        },
        {
            'id': 'mobile-developer',
            'title': 'Mobile Developer',
            'emoji': '',
            'tagline': 'Apps in the hands of millions.',
            'description': "You want your work in everyone's pocket. Focused on responsive Android/iOS apps.",
            'accent': '#e5e5e5',
            'match_tags': ['mobile-dev', 'ui-ux', 'gaming'],
            'tech_stack': ['Kotlin', 'Swift', 'Flutter'],
            'sort_order': 3,
        },
        {
            'id': 'ml-engineer',
            'title': 'ML / AI Engineer',
            'emoji': '',
            'tagline': 'Teaching machines to think.',
            'description': "You're curious about patterns and prediction. Building models that learn from data is your passion.",
            'accent': '#e5e5e5',
            'match_tags': ['machine-learning', 'data-analytics', 'competitive-programming'],
            'tech_stack': ['Python', 'PyTorch', 'Pandas'],
            'sort_order': 4,
        },
        {
            'id': 'data-analyst',
            'title': 'Data Analyst',
            'emoji': '',
            'tagline': 'Turning numbers into decisions.',
            'description': "You're great at finding the story behind the data and telling it clearly.",
            'accent': '#e5e5e5',
            'match_tags': ['data-analytics', 'writing', 'machine-learning'],
            'tech_stack': ['SQL', 'Python', 'Looker'],
            'sort_order': 5,
        },
        {
            'id': 'devops-engineer',
            'title': 'DevOps / Cloud Engineer',
            'emoji': '',
            'tagline': 'Automation, deploys, and 99.9% uptime.',
            'description': 'You love making systems run automatically and reliably, from CI/CD to cloud infrastructure.',
            'accent': '#e5e5e5',
            'match_tags': ['cloud-devops', 'open-source', 'cybersecurity'],
            'tech_stack': ['Docker', 'Kubernetes', 'Terraform'],
            'sort_order': 6,
        },
        {
            'id': 'security-engineer',
            'title': 'Security Engineer',
            'emoji': '',
            'tagline': 'The gatekeeper of the digital world.',
            'description': 'You think like an attacker in order to defend. Focused on system and network security.',
            'accent': '#e5e5e5',
            'match_tags': ['cybersecurity', 'competitive-programming', 'open-source'],
            'tech_stack': ['Linux', 'Python', 'Burp Suite'],
            'sort_order': 7,
        },
        {
            'id': 'game-developer',
            'title': 'Game Developer',
            'emoji': '',
            'tagline': 'Building worlds you can play.',
            'description': 'You want to combine logic, art, and story into a fun playing experience.',
            'accent': '#e5e5e5',
            'match_tags': ['game-dev', 'gaming', 'ui-ux', 'anime'],
            'tech_stack': ['Unity', 'C#', 'Godot'],
            'sort_order': 8,
        },
        {
            'id': 'ui-ux-designer',
            'title': 'UI/UX Designer',
            'emoji': '',
            'tagline': 'Empathy translated into design.',
            'description': 'You care about how people feel using a product. Research, wireframes, and prototypes.',
            'accent': '#e5e5e5',
            'match_tags': ['ui-ux', 'photography', 'writing'],
            'tech_stack': ['Figma', 'Framer', 'Miro'],
            'sort_order': 9,
        },
        {
            'id': 'fullstack-engineer',
            'title': 'Fullstack / Product Engineer',
            'emoji': '',
            'tagline': 'From idea to deploy, you can do it all.',
            'description': 'You love building whole features — frontend, backend, all the way to release. A product-minded generalist.',
            'accent': '#e5e5e5',
            'match_tags': ['web-dev', 'ui-ux', 'writing', 'open-source', 'cloud-devops'],
            'tech_stack': ['Next.js', 'Node.js', 'PostgreSQL'],
            'sort_order': 10,
        },
    ])

    # 2. HOBBIES
    hobbies_table = sa.table(
        'hobbies',
        sa.column('id', sa.Text),
        sa.column('label', sa.Text),
        sa.column('emoji', sa.Text),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(hobbies_table, [
        {'id': 'competitive-programming', 'label': 'Competitive Programming', 'emoji': '', 'sort_order': 1},
        {'id': 'web-dev', 'label': 'Web Development', 'emoji': '', 'sort_order': 2},
        {'id': 'mobile-dev', 'label': 'Mobile Dev', 'emoji': '', 'sort_order': 3},
        {'id': 'game-dev', 'label': 'Game Dev', 'emoji': '', 'sort_order': 4},
        {'id': 'machine-learning', 'label': 'Machine Learning', 'emoji': '', 'sort_order': 5},
        {'id': 'data-analytics', 'label': 'Data & Analytics', 'emoji': '', 'sort_order': 6},
        {'id': 'cybersecurity', 'label': 'Cybersecurity', 'emoji': '', 'sort_order': 7},
        {'id': 'cloud-devops', 'label': 'Cloud & DevOps', 'emoji': '', 'sort_order': 8},
        {'id': 'open-source', 'label': 'Open Source', 'emoji': '', 'sort_order': 9},
        {'id': 'ui-ux', 'label': 'UI/UX Design', 'emoji': '', 'sort_order': 10},
        {'id': 'photography', 'label': 'Photography', 'emoji': '', 'sort_order': 11},
        {'id': 'lofi-music', 'label': 'Lo-Fi & Music', 'emoji': '', 'sort_order': 12},
        {'id': 'writing', 'label': 'Writing & Blogging', 'emoji': '', 'sort_order': 13},
        {'id': 'anime', 'label': 'Anime & Manga', 'emoji': '', 'sort_order': 14},
        {'id': 'gaming', 'label': 'Gaming', 'emoji': '', 'sort_order': 15},
        {'id': 'coffee', 'label': 'Coffee Nerd', 'emoji': '', 'sort_order': 16},
    ])

    # 3. ONBOARDING QUESTIONS
    questions_table = sa.table(
        'onboarding_questions',
        sa.column('id', sa.Text),
        sa.column('text', sa.Text),
        sa.column('role_id', sa.Text),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(questions_table, [
        {'id': 'q1', 'text': "I enjoy designing and polishing an app's interface.", 'role_id': 'frontend-engineer', 'sort_order': 1},
        {'id': 'q2', 'text': 'I like building things that are instantly visible & interactive on screen.', 'role_id': 'frontend-engineer', 'sort_order': 2},
        {'id': 'q3', 'text': "I'm interested in designing data structures, APIs, and behind-the-scenes logic.", 'role_id': 'backend-engineer', 'sort_order': 3},
        {'id': 'q4', 'text': 'I enjoy thinking about system performance, security, and scalability.', 'role_id': 'backend-engineer', 'sort_order': 4},
        {'id': 'q5', 'text': "I'm curious about finding patterns in data and making predictions.", 'role_id': 'ml-engineer', 'sort_order': 5},
        {'id': 'q6', 'text': "I'm comfortable working with math, statistics, and model experiments.", 'role_id': 'ml-engineer', 'sort_order': 6},
        {'id': 'q7', 'text': 'I want to build apps used right from a phone.', 'role_id': 'mobile-developer', 'sort_order': 7},
        {'id': 'q8', 'text': 'I like optimizing the experience on mobile devices (Android/iOS).', 'role_id': 'mobile-developer', 'sort_order': 8},
    ])

    # 4. BADGES
    badges_table = sa.table(
        'badges',
        sa.column('id', sa.Text),
        sa.column('name', sa.Text),
        sa.column('description', sa.Text),
        sa.column('icon', sa.Text),
        sa.column('tier', sa.Enum('common', 'rare', 'epic', 'legendary', name='badge_tier')),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(badges_table, [
        {'id': 'first-commit', 'name': 'First Blood', 'description': 'Your first commit to a public repo.', 'icon': '', 'tier': 'common', 'sort_order': 1},
        {'id': 'streak-7', 'name': 'Consistent', 'description': 'A 7-day streak.', 'icon': '', 'tier': 'common', 'sort_order': 2},
        {'id': 'streak-30', 'name': 'On Fire', 'description': 'A 30-day streak.', 'icon': '', 'tier': 'rare', 'sort_order': 3},
        {'id': 'polyglot', 'name': 'Polyglot', 'description': 'Coded in 5+ different languages.', 'icon': '', 'tier': 'rare', 'sort_order': 4},
        {'id': 'contributor', 'name': 'Contributor', 'description': 'Merged a PR into an open-source project.', 'icon': '', 'tier': 'epic', 'sort_order': 5},
        {'id': 'rising-star', 'name': 'Rising Star', 'description': 'One of your repos hit 100 stars.', 'icon': '', 'tier': 'epic', 'sort_order': 6},
        {'id': 'night-owl', 'name': 'Night Owl', 'description': 'Committed at midnight 10 times.', 'icon': '', 'tier': 'common', 'sort_order': 7},
        {'id': 'mentor', 'name': 'Mentor', 'description': 'Helped 10 people in a discussion channel.', 'icon': '', 'tier': 'legendary', 'sort_order': 8},
    ])

    # 5. SERVERS & CHANNELS
    servers_table = sa.table(
        'servers',
        sa.column('id', sa.Text),
        sa.column('name', sa.Text),
        sa.column('initial', sa.Text),
        sa.column('color', sa.Text),
        sa.column('owner_id', sa.UUID),
        sa.column('is_team_community', sa.Boolean),
        sa.column('banned', sa.Boolean),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(servers_table, [
        {'id': 'itb', 'name': 'ITB Computer Science', 'initial': 'IT', 'color': '#e5e5e5', 'owner_id': None, 'is_team_community': False, 'banned': False, 'created_at': now},
        {'id': 'ui', 'name': 'UI Computer Science', 'initial': 'UI', 'color': '#e5e5e5', 'owner_id': None, 'is_team_community': False, 'banned': False, 'created_at': now},
        {'id': 'ugm', 'name': 'UGM Computer Science', 'initial': 'UG', 'color': '#e5e5e5', 'owner_id': None, 'is_team_community': False, 'banned': False, 'created_at': now},
    ])

    channels_table = sa.table(
        'channels',
        sa.column('id', sa.Text),
        sa.column('server_id', sa.Text),
        sa.column('name', sa.Text),
        sa.column('topic', sa.Text),
        sa.column('kind', sa.Enum('text', 'anon', name='channel_kind')),
        sa.column('sort_order', sa.Integer),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(channels_table, [
        {'id': 'general', 'server_id': 'itb', 'name': 'general', 'topic': 'General chat for campus folks', 'kind': 'text', 'sort_order': 1, 'created_at': now},
        {'id': 'ui-ux', 'server_id': 'itb', 'name': 'UI-UX', 'topic': 'Design, prototyping & Figma discussion', 'kind': 'text', 'sort_order': 2, 'created_at': now},
        {'id': 'loker', 'server_id': 'itb', 'name': 'jobs', 'topic': 'Internships, part-time & job openings', 'kind': 'text', 'sort_order': 3, 'created_at': now},
        {'id': 'frontend', 'server_id': 'itb', 'name': 'frontend', 'topic': 'React, Vue, Svelte & friends', 'kind': 'text', 'sort_order': 4, 'created_at': now},
        {'id': 'tanya-anonim', 'server_id': 'itb', 'name': 'ask-anon', 'topic': "Ask anything, the asker's identity stays hidden", 'kind': 'anon', 'sort_order': 5, 'created_at': now},
        {'id': 'ui-general', 'server_id': 'ui', 'name': 'general', 'topic': 'General chat for UI Computer Science', 'kind': 'text', 'sort_order': 1, 'created_at': now},
        {'id': 'ui-riset', 'server_id': 'ui', 'name': 'research', 'topic': 'Paper & research discussion', 'kind': 'text', 'sort_order': 2, 'created_at': now},
        {'id': 'ugm-general', 'server_id': 'ugm', 'name': 'general', 'topic': 'General chat for UGM Computer Science', 'kind': 'text', 'sort_order': 1, 'created_at': now},
    ])

    # 6. ROADMAPS
    roadmaps_table = sa.table(
        'roadmaps',
        sa.column('id', sa.Text),
        sa.column('role_id', sa.Text),
        sa.column('title', sa.Text),
        sa.column('emoji', sa.Text),
        sa.column('color', sa.Text),
        sa.column('description', sa.Text),
        sa.column('difficulty', sa.Enum('Beginner', 'Intermediate', 'Advanced', name='roadmap_difficulty')),
        sa.column('match_tags', postgresql.ARRAY(sa.Text)),
        sa.column('author', sa.Text),
        sa.column('style', postgresql.JSONB),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(roadmaps_table, [
        {
            'id': 'frontend',
            'role_id': 'frontend-engineer',
            'title': 'Frontend Engineer',
            'emoji': '',
            'color': '#e5e5e5',
            'description': 'Build interactive web interfaces — HTML, CSS, JS, React, all the way to deploy.',
            'difficulty': 'Beginner',
            'match_tags': ['web-dev', 'ui-ux', 'open-source', 'gaming'],
            'author': 'Dr. Andi Wijaya',
            'style': {},
            'created_at': now,
            'updated_at': now,
        },
        {
            'id': 'backend',
            'role_id': 'backend-engineer',
            'title': 'Backend Engineer',
            'emoji': '',
            'color': '#e5e5e5',
            'description': 'Build scalable APIs, databases, and the systems behind the scenes.',
            'difficulty': 'Intermediate',
            'match_tags': ['web-dev', 'competitive-programming', 'cloud-devops', 'open-source'],
            'author': 'Dr. Budi Santoso',
            'style': {},
            'created_at': now,
            'updated_at': now,
        },
        {
            'id': 'data',
            'role_id': 'ml-engineer',
            'title': 'Data & Machine Learning',
            'emoji': '',
            'color': '#e5e5e5',
            'description': 'Work with data and statistics, up to building models that learn on their own.',
            'difficulty': 'Intermediate',
            'match_tags': ['machine-learning', 'data-analytics', 'competitive-programming'],
            'author': 'Prof. Clara Halim',
            'style': {},
            'created_at': now,
            'updated_at': now,
        },
        {
            'id': 'mobile',
            'role_id': 'mobile-developer',
            'title': 'Mobile Developer',
            'emoji': '',
            'color': '#e5e5e5',
            'description': 'Build Android/iOS apps from scratch to publishing on the store.',
            'difficulty': 'Beginner',
            'match_tags': ['mobile-dev', 'ui-ux', 'gaming'],
            'author': 'Dr. Dewi Lestari',
            'style': {},
            'created_at': now,
            'updated_at': now,
        },
    ])

    # 6b. ROADMAP NODES & EDGES
    nodes_table = sa.table(
        'roadmap_nodes',
        sa.column('id', sa.UUID),
        sa.column('roadmap_id', sa.Text),
        sa.column('node_key', sa.Text),
        sa.column('title', sa.Text),
        sa.column('emoji', sa.Text),
        sa.column('x', sa.Float),
        sa.column('y', sa.Float),
        sa.column('group_name', sa.Text),
        sa.column('image', sa.Text),
        sa.column('title_inside', sa.Boolean),
        sa.column('always_unlocked', sa.Boolean),
        sa.column('optional', sa.Boolean),
        sa.column('article', sa.Text),
        sa.column('submission', postgresql.JSONB),
        sa.column('resources', postgresql.JSONB),
        sa.column('missions', postgresql.JSONB),
        sa.column('sort_order', sa.Integer),
    )

    edges_table = sa.table(
        'roadmap_edges',
        sa.column('id', sa.UUID),
        sa.column('roadmap_id', sa.Text),
        sa.column('edge_key', sa.Text),
        sa.column('source_key', sa.Text),
        sa.column('target_key', sa.Text),
        sa.column('dashed', sa.Boolean),
        sa.column('optional', sa.Boolean),
        sa.column('animated', sa.Boolean),
    )

    # Frontend nodes & edges
    frontend_nodes = [
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'html-css',
            'title': 'HTML & CSS',
            'emoji': '',
            'x': 50.0,
            'y': 6.0,
            'group_name': 'Fundamentals',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## HTML & CSS\n\nFondasi setiap halaman web. **HTML** menyusun struktur, **CSS** mengatur tampilan.\n\n### Yang dipelajari\n- Semantic HTML (`header`, `nav`, `main`, `footer`)\n- Box model, Flexbox, dan Grid\n- Responsive design & media queries\n\n> Tips: bikin ulang layout website favoritmu untuk latihan.\n\nReferensi: [MDN HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML) · [web.dev CSS](https://web.dev/learn/css)",
            'submission': {
                'type': 'quiz',
                'passingScore': 50,
                'questions': [
                    {
                        'id': 'q1',
                        'question': 'Properti CSS untuk membuat layout fleksibel satu dimensi?',
                        'options': ['display: block', 'display: flex', 'float: left', 'position: absolute'],
                        'correctIndex': 1,
                    },
                    {
                        'id': 'q2',
                        'question': 'Tag HTML yang semantik untuk navigasi?',
                        'options': ['<div>', '<nav>', '<span>', '<b>'],
                        'correctIndex': 1,
                    },
                ],
            },
            'resources': None,
            'missions': None,
            'sort_order': 0,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'javascript',
            'title': 'JavaScript',
            'emoji': '',
            'x': 50.0,
            'y': 20.0,
            'group_name': 'Fundamentals',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## JavaScript\n\nBahasa yang bikin web jadi **interaktif** — event, DOM, fetch API, dan async.\n\n### Yang dipelajari\n- Variabel, function, array & object\n- Manipulasi DOM & event handling\n- `fetch` + async/await\n\n**Latihan:** bikin aplikasi to-do sederhana tanpa framework, lalu push ke GitHub.",
            'submission': {'type': 'text', 'prompt': 'Tempel link GitHub repo aplikasi to-do buatanmu.'},
            'resources': None,
            'missions': None,
            'sort_order': 1,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'git',
            'title': 'Git & GitHub',
            'emoji': '',
            'x': 84.0,
            'y': 20.0,
            'group_name': 'Fundamentals',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## Git & GitHub\n\nVersion control wajib buat semua dev. Kelola perubahan kode & kolaborasi.\n\n### Yang dipelajari\n- `commit`, `branch`, `merge`, `pull request`\n- Menyelesaikan merge conflict\n\nReferensi: [Learn Git Branching](https://learngitbranching.js.org)",
            'submission': {'type': 'text', 'prompt': 'Tempel link profil GitHub-mu.'},
            'resources': None,
            'missions': None,
            'sort_order': 2,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'typescript',
            'title': 'TypeScript',
            'emoji': '',
            'x': 28.0,
            'y': 42.0,
            'group_name': 'Core',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## TypeScript\n\nJavaScript **plus tipe statis** — bikin kode lebih aman & enak di-maintain.\n\n### Yang dipelajari\n- Tipe dasar, interface, dan generic\n- Type narrowing & utility types\n\nReferensi: [TS Handbook](https://www.typescriptlang.org/docs/handbook/intro.html)",
            'submission': {'type': 'checkmark'},
            'resources': None,
            'missions': None,
            'sort_order': 3,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'tailwind',
            'title': 'Tailwind CSS',
            'emoji': '',
            'x': 72.0,
            'y': 42.0,
            'group_name': 'Core',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## Tailwind CSS\n\nUtility-first CSS framework — styling cepat langsung di markup.\n\n### Yang dipelajari\n- Utility class & responsive prefix\n- Dark mode dengan theme token\n\nReferensi: [Tailwind Docs](https://tailwindcss.com/docs)",
            'submission': {'type': 'checkmark'},
            'resources': None,
            'missions': None,
            'sort_order': 4,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'react',
            'title': 'React',
            'emoji': '',
            'x': 50.0,
            'y': 56.0,
            'group_name': 'Core',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## React\n\nLibrary UI berbasis **komponen**. Kelola state dengan hooks.\n\n### Yang dipelajari\n- Komponen, props, dan `useState`/`useEffect`\n- Lifting state & composition\n\n**Latihan:** bikin komponen reusable + form dengan hooks.",
            'submission': {'type': 'text', 'prompt': 'Tempel link repo komponen/app React buatanmu.'},
            'resources': None,
            'missions': None,
            'sort_order': 5,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'state-mgmt',
            'title': 'Data & State',
            'emoji': '',
            'x': 22.0,
            'y': 78.0,
            'group_name': 'Advanced',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## Data & State Management\n\nAmbil data server & kelola state global tanpa pusing.\n\n### Yang dipelajari\n- Data fetching + caching (TanStack Query)\n- Global state (Zustand)\n\nReferensi: [TanStack Query](https://tanstack.com/query/latest)",
            'submission': {'type': 'checkmark'},
            'resources': None,
            'missions': None,
            'sort_order': 6,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'nextjs',
            'title': 'Next.js',
            'emoji': '',
            'x': 50.0,
            'y': 78.0,
            'group_name': 'Advanced',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## Next.js\n\nFramework React untuk produksi: routing, server components, dan SSR.\n\n### Yang dipelajari\n- App Router & server components\n- Data fetching + routing dinamis\n\n**Latihan:** bikin app kecil, lalu screenshot hasilnya.",
            'submission': {'type': 'file', 'prompt': 'Upload screenshot aplikasi Next.js buatanmu (png/jpg).'},
            'resources': None,
            'missions': None,
            'sort_order': 7,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'testing',
            'title': 'Testing',
            'emoji': '',
            'x': 78.0,
            'y': 78.0,
            'group_name': 'Advanced',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': True,
            'article': "## Testing\n\nPastikan aplikasi tetap benar saat berubah. Unit & integration test.\n\n### Yang dipelajari\n- Testing Library + Vitest\n- Menulis test untuk komponen & alur user\n\nReferensi: [Testing Library](https://testing-library.com)",
            'submission': {
                'type': 'quiz',
                'passingScore': 50,
                'questions': [
                    {
                        'id': 'q1',
                        'question': 'Library populer untuk testing komponen React?',
                        'options': ['jQuery', 'Testing Library', 'Lodash', 'Axios'],
                        'correctIndex': 1,
                    },
                    {
                        'id': 'q2',
                        'question': 'Jenis test yang menguji satu fungsi/komponen terisolasi?',
                        'options': ['End-to-end test', 'Unit test', 'Load test', 'Manual test'],
                        'correctIndex': 1,
                    },
                ],
            },
            'resources': None,
            'missions': None,
            'sort_order': 8,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'frontend',
            'node_key': 'deployment',
            'title': 'Deploy & CI/CD',
            'emoji': '',
            'x': 50.0,
            'y': 98.0,
            'group_name': 'Advanced',
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': "## Deploy & CI/CD\n\nRilis aplikasimu ke internet & otomasi build/test tiap push.\n\n### Yang dipelajari\n- Deploy ke Vercel/Netlify\n- CI dengan GitHub Actions\n\n**Latihan:** deploy salah satu project-mu, lalu tempel URL-nya.",
            'submission': {'type': 'text', 'prompt': 'Tempel URL project yang sudah kamu deploy (mis. Vercel).'},
            'resources': None,
            'missions': None,
            'sort_order': 9,
        },
    ]

    frontend_edges = [
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e1', 'source_key': 'html-css', 'target_key': 'javascript', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e2', 'source_key': 'html-css', 'target_key': 'git', 'dashed': True, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e3', 'source_key': 'javascript', 'target_key': 'typescript', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e4', 'source_key': 'javascript', 'target_key': 'tailwind', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e5', 'source_key': 'typescript', 'target_key': 'react', 'dashed': False, 'optional': False, 'animated': True},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e6', 'source_key': 'react', 'target_key': 'state-mgmt', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e7', 'source_key': 'react', 'target_key': 'nextjs', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e8', 'source_key': 'tailwind', 'target_key': 'nextjs', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e9', 'source_key': 'react', 'target_key': 'testing', 'dashed': True, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e10', 'source_key': 'nextjs', 'target_key': 'deployment', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'frontend', 'edge_key': 'e11', 'source_key': 'git', 'target_key': 'deployment', 'dashed': False, 'optional': True, 'animated': False},
    ]

    # Backend nodes & edges
    backend_nodes = [
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'bahasa',
            'title': 'Bahasa (Go/Python)',
            'emoji': '',
            'x': 50.0,
            'y': 7.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'A Tour of Go', 'url': 'https://go.dev/tour/'},
                {'label': 'Python Docs', 'url': 'https://docs.python.org/3/tutorial/'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Bikin CLI sederhana'},
                {'id': 'm2', 'text': 'Selesaikan 5 soal algoritma dasar'},
            ],
            'sort_order': 0,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'rest-api',
            'title': 'HTTP & REST API',
            'emoji': '',
            'x': 38.0,
            'y': 24.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'MDN: HTTP', 'url': 'https://developer.mozilla.org/en-US/docs/Web/HTTP'},
                {'label': 'REST API Best Practices', 'url': 'https://restfulapi.net'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Bikin API CRUD lengkap'},
                {'id': 'm2', 'text': 'Dokumentasikan pakai OpenAPI/Swagger'},
            ],
            'sort_order': 1,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'database',
            'title': 'Database & SQL',
            'emoji': '',
            'x': 76.0,
            'y': 22.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'PostgreSQL Tutorial', 'url': 'https://www.postgresqltutorial.com'},
                {'label': 'SQLBolt', 'url': 'https://sqlbolt.com'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Desain skema relasional'},
                {'id': 'm2', 'text': 'Tulis query JOIN kompleks'},
            ],
            'sort_order': 2,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'auth',
            'title': 'Auth & Security',
            'emoji': '',
            'x': 22.0,
            'y': 44.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'JWT.io', 'url': 'https://jwt.io/introduction'},
                {'label': 'OWASP Top 10', 'url': 'https://owasp.org/www-project-top-ten/'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Implementasi login pakai JWT'},
                {'id': 'm2', 'text': 'Hash password dengan bcrypt/argon2'},
            ],
            'sort_order': 3,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'caching',
            'title': 'Caching & Queue',
            'emoji': '',
            'x': 58.0,
            'y': 44.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Redis Docs', 'url': 'https://redis.io/docs/'},
                {'label': 'RabbitMQ Tutorial', 'url': 'https://www.rabbitmq.com/getstarted.html'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Cache response pakai Redis'},
                {'id': 'm2', 'text': 'Proses job async lewat message queue'},
            ],
            'sort_order': 4,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'testing',
            'title': 'Testing',
            'emoji': '',
            'x': 84.0,
            'y': 60.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Testing in Go', 'url': 'https://go.dev/doc/tutorial/add-a-test'},
                {'label': 'Postman', 'url': 'https://learning.postman.com'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Tulis unit test untuk service'},
                {'id': 'm2', 'text': 'Integration test 1 endpoint'},
            ],
            'sort_order': 5,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'backend',
            'node_key': 'deploy',
            'title': 'Deploy & Docker',
            'emoji': '',
            'x': 50.0,
            'y': 82.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Docker Docs', 'url': 'https://docs.docker.com/get-started/'},
                {'label': 'Railway', 'url': 'https://docs.railway.app'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Containerize app pakai Docker'},
                {'id': 'm2', 'text': 'Deploy ke cloud + kelola env vars'},
            ],
            'sort_order': 6,
        },
    ]

    backend_edges = [
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-bahasa-rest-api', 'source_key': 'bahasa', 'target_key': 'rest-api', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-bahasa-database', 'source_key': 'bahasa', 'target_key': 'database', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-rest-api-auth', 'source_key': 'rest-api', 'target_key': 'auth', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-rest-api-caching', 'source_key': 'rest-api', 'target_key': 'caching', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-database-caching', 'source_key': 'database', 'target_key': 'caching', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-database-testing', 'source_key': 'database', 'target_key': 'testing', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-auth-deploy', 'source_key': 'auth', 'target_key': 'deploy', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-caching-deploy', 'source_key': 'caching', 'target_key': 'deploy', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'backend', 'edge_key': 'e-testing-deploy', 'source_key': 'testing', 'target_key': 'deploy', 'dashed': False, 'optional': False, 'animated': False},
    ]

    # Data roadmap nodes & edges
    data_nodes = [
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'python',
            'title': 'Python & NumPy',
            'emoji': '',
            'x': 50.0,
            'y': 7.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Python.org Tutorial', 'url': 'https://docs.python.org/3/tutorial/'},
                {'label': 'NumPy Quickstart', 'url': 'https://numpy.org/doc/stable/user/quickstart.html'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Olah array pakai NumPy'},
                {'id': 'm2', 'text': 'Selesaikan 10 latihan Python'},
            ],
            'sort_order': 0,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'statistik',
            'title': 'Statistik & Probabilitas',
            'emoji': '',
            'x': 26.0,
            'y': 26.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'StatQuest (YouTube)', 'url': 'https://www.youtube.com/c/joshstarmer'},
                {'label': 'Khan Academy Statistics', 'url': 'https://www.khanacademy.org/math/statistics-probability'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Hitung mean/median/std sebuah dataset'},
                {'id': 'm2', 'text': 'Pahami & plot distribusi normal'},
            ],
            'sort_order': 1,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'pandas',
            'title': 'Pandas & Wrangling',
            'emoji': '',
            'x': 74.0,
            'y': 26.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Pandas Docs', 'url': 'https://pandas.pydata.org/docs/'},
                {'label': 'Kaggle: Pandas', 'url': 'https://www.kaggle.com/learn/pandas'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Bersihkan dataset yang berantakan'},
                {'id': 'm2', 'text': 'Agregasi data pakai groupby'},
            ],
            'sort_order': 2,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'visualisasi',
            'title': 'Visualisasi Data',
            'emoji': '',
            'x': 50.0,
            'y': 46.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Matplotlib', 'url': 'https://matplotlib.org/stable/tutorials/index.html'},
                {'label': 'Seaborn', 'url': 'https://seaborn.pydata.org/tutorial.html'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Bikin 3 jenis chart dari data nyata'},
                {'id': 'm2', 'text': 'Susun dashboard eksplorasi sederhana'},
            ],
            'sort_order': 3,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'ml',
            'title': 'Machine Learning',
            'emoji': '',
            'x': 34.0,
            'y': 66.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'scikit-learn', 'url': 'https://scikit-learn.org/stable/user_guide.html'},
                {'label': 'Andrew Ng ML', 'url': 'https://www.coursera.org/learn/machine-learning'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Latih model regresi & klasifikasi'},
                {'id': 'm2', 'text': 'Evaluasi pakai train/test split'},
            ],
            'sort_order': 4,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'data',
            'node_key': 'deploy-ml',
            'title': 'MLOps & Deploy',
            'emoji': '',
            'x': 62.0,
            'y': 84.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Streamlit', 'url': 'https://docs.streamlit.io'},
                {'label': 'FastAPI', 'url': 'https://fastapi.tiangolo.com'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Serve model lewat REST API'},
                {'id': 'm2', 'text': 'Bikin demo app pakai Streamlit'},
            ],
            'sort_order': 5,
        },
    ]

    data_edges = [
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-python-statistik', 'source_key': 'python', 'target_key': 'statistik', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-python-pandas', 'source_key': 'python', 'target_key': 'pandas', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-pandas-visualisasi', 'source_key': 'pandas', 'target_key': 'visualisasi', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-statistik-ml', 'source_key': 'statistik', 'target_key': 'ml', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-pandas-ml', 'source_key': 'pandas', 'target_key': 'ml', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-ml-deploy-ml', 'source_key': 'ml', 'target_key': 'deploy-ml', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'data', 'edge_key': 'e-visualisasi-deploy-ml', 'source_key': 'visualisasi', 'target_key': 'deploy-ml', 'dashed': False, 'optional': False, 'animated': False},
    ]

    # Mobile nodes & edges
    mobile_nodes = [
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'dasar',
            'title': 'Dart / Kotlin Dasar',
            'emoji': '',
            'x': 50.0,
            'y': 7.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Dart Language Tour', 'url': 'https://dart.dev/language'},
                {'label': 'Kotlin Docs', 'url': 'https://kotlinlang.org/docs/home.html'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Bikin program konsol sederhana'},
                {'id': 'm2', 'text': 'Pahami konsep OOP dasar'},
            ],
            'sort_order': 0,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'ui',
            'title': 'UI & Layout',
            'emoji': '',
            'x': 32.0,
            'y': 28.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Flutter Widgets', 'url': 'https://docs.flutter.dev/ui/widgets'},
                {'label': 'Jetpack Compose', 'url': 'https://developer.android.com/jetpack/compose/documentation'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Susun layout responsif'},
                {'id': 'm2', 'text': 'Kloning 1 screen aplikasi populer'},
            ],
            'sort_order': 1,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'state',
            'title': 'State Management',
            'emoji': '',
            'x': 68.0,
            'y': 28.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Riverpod', 'url': 'https://riverpod.dev'},
                {'label': 'Android ViewModel', 'url': 'https://developer.android.com/topic/libraries/architecture/viewmodel'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Kelola state form multi-step'},
                {'id': 'm2', 'text': 'Pisahkan logic dari UI'},
            ],
            'sort_order': 2,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'api',
            'title': 'API & Local Storage',
            'emoji': '',
            'x': 32.0,
            'y': 50.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Dio / Retrofit', 'url': 'https://pub.dev/packages/dio'},
                {'label': 'SQLite / Room', 'url': 'https://developer.android.com/training/data-storage/room'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Konsumsi REST API & render list'},
                {'id': 'm2', 'text': 'Simpan data offline lokal'},
            ],
            'sort_order': 3,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'native',
            'title': 'Fitur Native',
            'emoji': '',
            'x': 68.0,
            'y': 52.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Camera Plugin', 'url': 'https://pub.dev/packages/camera'},
                {'label': 'Push Notification', 'url': 'https://firebase.google.com/docs/cloud-messaging'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Akses kamera/galeri perangkat'},
                {'id': 'm2', 'text': 'Kirim notifikasi lokal'},
            ],
            'sort_order': 4,
        },
        {
            'id': uuid.uuid4(),
            'roadmap_id': 'mobile',
            'node_key': 'publish',
            'title': 'Publish ke Store',
            'emoji': '',
            'x': 50.0,
            'y': 80.0,
            'group_name': None,
            'image': None,
            'title_inside': False,
            'always_unlocked': False,
            'optional': False,
            'article': None,
            'submission': None,
            'resources': [
                {'label': 'Google Play Console', 'url': 'https://developer.android.com/distribute/console'},
                {'label': 'App Store Connect', 'url': 'https://developer.apple.com/app-store-connect/'},
            ],
            'missions': [
                {'id': 'm1', 'text': 'Build release yang ter-sign'},
                {'id': 'm2', 'text': 'Siapkan aset store & submit'},
            ],
            'sort_order': 5,
        },
    ]

    mobile_edges = [
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-dasar-ui', 'source_key': 'dasar', 'target_key': 'ui', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-dasar-state', 'source_key': 'dasar', 'target_key': 'state', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-ui-api', 'source_key': 'ui', 'target_key': 'api', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-state-native', 'source_key': 'state', 'target_key': 'native', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-api-native', 'source_key': 'api', 'target_key': 'native', 'dashed': False, 'optional': False, 'animated': False},
        {'id': uuid.uuid4(), 'roadmap_id': 'mobile', 'edge_key': 'e-native-publish', 'source_key': 'native', 'target_key': 'publish', 'dashed': False, 'optional': False, 'animated': False},
    ]

    all_nodes = frontend_nodes + backend_nodes + data_nodes + mobile_nodes
    all_edges = frontend_edges + backend_edges + data_edges + mobile_edges

    op.bulk_insert(nodes_table, all_nodes)
    op.bulk_insert(edges_table, all_edges)

    # 7. INTERNSHIP CONTACTS
    internships_table = sa.table(
        'internship_contacts',
        sa.column('id', sa.Text),
        sa.column('company', sa.Text),
        sa.column('position', sa.Text),
        sa.column('role_id', sa.Text),
        sa.column('location', sa.Text),
        sa.column('type', sa.Text),
        sa.column('pic', sa.Text),
        sa.column('contact', sa.Text),
        sa.column('note', sa.Text),
    )
    op.bulk_insert(internships_table, [
        {'id': 'fe1', 'company': 'Tokopedia', 'position': 'Frontend Engineer Intern', 'role_id': 'frontend-engineer', 'location': 'Jakarta', 'type': 'Hybrid', 'pic': 'Rina — Talent Acquisition', 'contact': 'internship@tokopedia.com', 'note': 'Sebut kamu dari Sepaham + lampirkan roadmap-mu.'},
        {'id': 'fe2', 'company': 'Gojek', 'position': 'Web Frontend Intern', 'role_id': 'frontend-engineer', 'location': 'Jakarta', 'type': 'On-site', 'pic': 'Dimas — Engineering Manager', 'contact': 'https://www.gojek.io/careers', 'note': 'Buka lowongan tiap kuartal.'},
        {'id': 'fe3', 'company': 'Ruangguru', 'position': 'Frontend Intern (React)', 'role_id': 'frontend-engineer', 'location': 'Remote', 'type': 'Remote', 'pic': 'Tania — Recruiter', 'contact': '+62 812-3456-7890', 'note': 'Chat WA, jam kerja 09.00–17.00.'},
        {'id': 'be1', 'company': 'Xendit', 'position': 'Backend Engineer Intern', 'role_id': 'backend-engineer', 'location': 'Jakarta', 'type': 'Hybrid', 'pic': 'Kevin — Backend Lead', 'contact': 'careers@xendit.co', 'note': 'Fokus Go & sistem pembayaran.'},
        {'id': 'be2', 'company': 'Traveloka', 'position': 'Software Engineer Intern (Backend)', 'role_id': 'backend-engineer', 'location': 'Jakarta', 'type': 'Hybrid', 'pic': 'Sari — Recruiter', 'contact': 'internship@traveloka.com', 'note': None},
        {'id': 'ml1', 'company': 'Kata.ai', 'position': 'ML Engineer Intern', 'role_id': 'ml-engineer', 'location': 'Jakarta', 'type': 'Remote', 'pic': 'Adi — AI Team', 'contact': 'hello@kata.ai', 'note': 'Bawa portofolio project ML.'},
        {'id': 'ml2', 'company': 'Bukalapak', 'position': 'Data Science Intern', 'role_id': 'ml-engineer', 'location': 'Jakarta', 'type': 'Hybrid', 'pic': 'Maya — Data Team', 'contact': 'https://careers.bukalapak.com', 'note': None},
        {'id': 'mo1', 'company': 'DANA', 'position': 'Android Engineer Intern', 'role_id': 'mobile-developer', 'location': 'Jakarta', 'type': 'On-site', 'pic': 'Bagus — Mobile Lead', 'contact': '081298765432', 'note': 'Kotlin & Jetpack Compose diutamakan. Chat via WA.'},
        {'id': 'mo2', 'company': 'Blibli', 'position': 'Mobile Engineer Intern', 'role_id': 'mobile-developer', 'location': 'Jakarta', 'type': 'Hybrid', 'pic': 'Nina — Recruiter', 'contact': 'internship@blibli.com', 'note': None},
    ])

    # 8. AI FEED: QUOTES & INTERNSHIPS
    dev_quotes_table = sa.table(
        'dev_quotes',
        sa.column('id', sa.UUID),
        sa.column('text', sa.Text),
        sa.column('author', sa.Text),
    )
    op.bulk_insert(dev_quotes_table, [
        {'id': uuid.uuid4(), 'text': 'Talk is cheap. Show me the code.', 'author': 'Linus Torvalds'},
        {'id': uuid.uuid4(), 'text': 'First, solve the problem. Then, write the code.', 'author': 'John Johnson'},
        {'id': uuid.uuid4(), 'text': "Code is like humor. When you have to explain it, it's bad.", 'author': 'Cory House'},
        {'id': uuid.uuid4(), 'text': 'A programmer is a machine that turns coffee into code.', 'author': 'Anonymous'},
        {'id': uuid.uuid4(), 'text': 'Simplicity is the soul of efficiency.', 'author': 'Austin Freeman'},
    ])

    ai_internships_table = sa.table(
        'ai_internships',
        sa.column('id', sa.Text),
        sa.column('company', sa.Text),
        sa.column('emoji', sa.Text),
        sa.column('role', sa.Text),
        sa.column('location', sa.Text),
        sa.column('type', sa.Text),
        sa.column('match_percent', sa.Integer),
        sa.column('tags', postgresql.ARRAY(sa.Text)),
    )
    op.bulk_insert(ai_internships_table, [
        {'id': 'i1', 'company': 'Tokopedia', 'emoji': '', 'role': 'Frontend Engineer Intern', 'location': 'Jakarta', 'type': 'Hybrid', 'match_percent': 92, 'tags': ['React', 'TypeScript', 'Tailwind']},
        {'id': 'i2', 'company': 'Ruangguru', 'emoji': '', 'role': 'Fullstack Engineer Intern', 'location': 'Remote', 'type': 'Remote', 'match_percent': 85, 'tags': ['Next.js', 'Node.js', 'PostgreSQL']},
        {'id': 'i3', 'company': 'Gojek', 'emoji': '', 'role': 'Mobile Engineer Intern', 'location': 'Jakarta', 'type': 'On-site', 'match_percent': 74, 'tags': ['Flutter', 'Kotlin', 'Firebase']},
        {'id': 'i4', 'company': 'Xendit', 'emoji': '', 'role': 'Backend Engineer Intern', 'location': 'Jakarta', 'type': 'Hybrid', 'match_percent': 68, 'tags': ['Go', 'Rust', 'Docker']},
    ])

    # 9. LO-FI TRACKS
    lofi_table = sa.table(
        'lofi_tracks',
        sa.column('id', sa.Text),
        sa.column('title', sa.Text),
        sa.column('artist', sa.Text),
    )
    op.bulk_insert(lofi_table, [
        {'id': 't1', 'title': 'Late Night Commit', 'artist': 'Lo-Fi Dev'},
        {'id': 't2', 'title': 'Coffee & Compile', 'artist': 'ChillCode'},
        {'id': 't3', 'title': 'Debugging Rain', 'artist': 'Ambient Stack'},
        {'id': 't4', 'title': 'Deploy at Dawn', 'artist': 'Synth Ops'},
    ])

    # 10. COLLAB REQUESTS & APPLICANTS
    collab_req_table = sa.table(
        'collab_requests',
        sa.column('id', sa.UUID),
        sa.column('author_id', sa.UUID),
        sa.column('author_name', sa.Text),
        sa.column('author_avatar', sa.Text),
        sa.column('author_role', sa.Text),
        sa.column('title', sa.Text),
        sa.column('description', sa.Text),
        sa.column('needed_roles', postgresql.ARRAY(sa.Text)),
        sa.column('tech_stack', postgresql.ARRAY(sa.Text)),
        sa.column('tags', postgresql.ARRAY(sa.Text)),
        sa.column('repo_url', sa.Text),
        sa.column('community_id', sa.Text),
        sa.column('members_current', sa.Integer),
        sa.column('members_needed', sa.Integer),
        sa.column('status', sa.Enum('open', 'full', name='collab_status')),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )

    c1_id = uuid.UUID('a0000000-0000-4000-8000-0000000000c1')
    c2_id = uuid.UUID('a0000000-0000-4000-8000-0000000000c2')
    c3_id = uuid.UUID('a0000000-0000-4000-8000-0000000000c3')
    c4_id = uuid.UUID('a0000000-0000-4000-8000-0000000000c4')
    c5_id = uuid.UUID('a0000000-0000-4000-8000-0000000000c5')

    op.bulk_insert(collab_req_table, [
        {
            'id': c1_id,
            'author_id': None,
            'author_name': 'Kevin Wijaya',
            'author_avatar': 'https://i.pravatar.cc/64?img=32',
            'author_role': 'Frontend',
            'title': 'Aplikasi Absensi Kelas pakai QR',
            'description': 'Bikin app absensi berbasis QR buat tugas besar Rekayasa Perangkat Lunak. Butuh yang jago backend & mobile, deadline 6 minggu.',
            'needed_roles': ['Backend', 'Mobile'],
            'tech_stack': ['Go', 'Flutter'],
            'tags': ['Tugas Besar'],
            'repo_url': 'https://github.com/kevinw/absensi-qr',
            'community_id': None,
            'members_current': 2,
            'members_needed': 4,
            'status': 'open',
            'created_at': now - timedelta(minutes=30),
        },
        {
            'id': c2_id,
            'author_id': None,
            'author_name': 'Nabila Zahra',
            'author_avatar': 'https://i.pravatar.cc/64?img=31',
            'author_role': 'Product',
            'title': 'Startup Marketplace Jasa Mahasiswa',
            'description': 'Serius mau bangun startup marketplace jasa antar mahasiswa (join tim, split equity). Cari co-founder teknis & desainer yang komit jangka panjang.',
            'needed_roles': ['Fullstack', 'UI/UX'],
            'tech_stack': ['Next.js', 'PostgreSQL'],
            'tags': ['Startup'],
            'repo_url': None,
            'community_id': None,
            'members_current': 1,
            'members_needed': 3,
            'status': 'open',
            'created_at': now - timedelta(minutes=120),
        },
        {
            'id': c3_id,
            'author_id': None,
            'author_name': 'Bagas Prasetyo',
            'author_avatar': 'https://i.pravatar.cc/64?img=68',
            'author_role': 'Backend',
            'title': 'Game Edukasi buat Lomba Hackathon',
            'description': 'Ikut hackathon bulan depan, tema teknologi pendidikan. Bikin game edukasi anak SD. Butuh 1 game dev & 1 artist.',
            'needed_roles': ['Game Dev', 'Artist'],
            'tech_stack': ['Unity', 'C#'],
            'tags': ['Hackathon'],
            'repo_url': None,
            'community_id': None,
            'members_current': 2,
            'members_needed': 4,
            'status': 'open',
            'created_at': now - timedelta(minutes=240),
        },
        {
            'id': c4_id,
            'author_id': None,
            'author_name': 'Dinda Ayu',
            'author_avatar': 'https://i.pravatar.cc/64?img=47',
            'author_role': 'UI/UX',
            'title': 'Web Portofolio Komunitas Open Source',
            'description': 'Bikin website showcase project open-source anak kampus. Santai, buat belajar bareng & nambah portofolio.',
            'needed_roles': ['Frontend', 'Backend'],
            'tech_stack': ['React', 'Node.js'],
            'tags': ['Open Source', 'Santai'],
            'repo_url': 'https://github.com/dindaa/oss-showcase',
            'community_id': None,
            'members_current': 3,
            'members_needed': 3,
            'status': 'full',
            'created_at': now - timedelta(minutes=600),
        },
        {
            'id': c5_id,
            'author_id': None,
            'author_name': 'Salsabila',
            'author_avatar': 'https://i.pravatar.cc/64?img=44',
            'author_role': 'Data Scientist',
            'title': 'Aplikasi Deteksi Penyakit Tanaman (ML)',
            'description': 'Project ML klasifikasi penyakit daun pakai CNN, buat skripsi + submit ke jurnal. Butuh partner yang ngerti data & deployment.',
            'needed_roles': ['Data/ML', 'Backend'],
            'tech_stack': ['Python', 'PyTorch'],
            'tags': ['Skripsi', 'Riset'],
            'repo_url': 'https://github.com/salsa/leaf-disease-cnn',
            'community_id': None,
            'members_current': 1,
            'members_needed': 2,
            'status': 'open',
            'created_at': now - timedelta(minutes=45),
        },
    ])

    collab_app_table = sa.table(
        'collab_applicants',
        sa.column('id', sa.UUID),
        sa.column('request_id', sa.UUID),
        sa.column('user_id', sa.UUID),
        sa.column('name', sa.Text),
        sa.column('avatar', sa.Text),
        sa.column('role', sa.Text),
        sa.column('message', sa.Text),
        sa.column('status', sa.Enum('pending', 'accepted', 'rejected', name='applicant_status')),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(collab_app_table, [
        {'id': uuid.uuid4(), 'request_id': c1_id, 'user_id': None, 'name': 'Rina Melati', 'avatar': 'https://i.pravatar.cc/64?img=20', 'role': 'Backend', 'message': 'Tertarik bantu backend-nya!', 'status': 'pending', 'created_at': now - timedelta(minutes=20)},
        {'id': uuid.uuid4(), 'request_id': c1_id, 'user_id': None, 'name': 'Yoga Pratama', 'avatar': 'https://i.pravatar.cc/64?img=52', 'role': 'Mobile', 'message': 'Bisa handle Flutter.', 'status': 'pending', 'created_at': now - timedelta(minutes=15)},
        {'id': uuid.uuid4(), 'request_id': c1_id, 'user_id': None, 'name': 'Aditya Nugroho', 'avatar': 'https://i.pravatar.cc/64?img=11', 'role': 'Backend', 'message': 'Go developer di sini.', 'status': 'pending', 'created_at': now - timedelta(minutes=10)},
        {'id': uuid.uuid4(), 'request_id': c2_id, 'user_id': None, 'name': 'Putri Ananda', 'avatar': 'https://i.pravatar.cc/64?img=25', 'role': 'UI/UX', 'message': 'Desainer, mau ikut!', 'status': 'pending', 'created_at': now - timedelta(minutes=90)},
        {'id': uuid.uuid4(), 'request_id': c2_id, 'user_id': None, 'name': 'Reza Fauzan', 'avatar': 'https://i.pravatar.cc/64?img=33', 'role': 'Fullstack', 'message': 'Komit jangka panjang.', 'status': 'pending', 'created_at': now - timedelta(minutes=60)},
        {'id': uuid.uuid4(), 'request_id': c3_id, 'user_id': None, 'name': 'Citra Dewi', 'avatar': 'https://i.pravatar.cc/64?img=48', 'role': 'Artist', 'message': 'Bisa bikin aset game.', 'status': 'pending', 'created_at': now - timedelta(minutes=120)},
        {'id': uuid.uuid4(), 'request_id': c5_id, 'user_id': None, 'name': 'Melati Sari', 'avatar': 'https://i.pravatar.cc/64?img=25', 'role': 'Data/ML', 'message': 'Ngerti CNN & deployment.', 'status': 'pending', 'created_at': now - timedelta(minutes=30)},
    ])

    # 11. MESSAGES
    messages_table = sa.table(
        'messages',
        sa.column('id', sa.UUID),
        sa.column('channel_id', sa.Text),
        sa.column('parent_id', sa.UUID),
        sa.column('author_id', sa.UUID),
        sa.column('author_name', sa.Text),
        sa.column('author_avatar', sa.Text),
        sa.column('body', sa.Text),
        sa.column('code_language', sa.Text),
        sa.column('code_content', sa.Text),
        sa.column('attachment_name', sa.Text),
        sa.column('attachment_kind', sa.Text),
        sa.column('attachment_size', sa.Text),
        sa.column('anonymous', sa.Boolean),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )

    f1_id = uuid.UUID('b0000000-0000-4000-8000-0000000000f1')
    op.bulk_insert(messages_table, [
        {
            'id': uuid.uuid4(),
            'channel_id': 'general',
            'parent_id': None,
            'author_id': None,
            'author_name': 'Rangga Pratama',
            'author_avatar': 'https://i.pravatar.cc/64?img=13',
            'body': 'Halo semua! Ada yang lagi ngerjain tugas Sistem Basis Data?',
            'code_language': None,
            'code_content': None,
            'attachment_name': None,
            'attachment_kind': None,
            'attachment_size': None,
            'anonymous': False,
            'created_at': now - timedelta(minutes=55),
        },
        {
            'id': uuid.uuid4(),
            'channel_id': 'general',
            'parent_id': None,
            'author_id': None,
            'author_name': 'Nadia Putri',
            'author_avatar': 'https://i.pravatar.cc/64?img=45',
            'body': 'Aku baru mulai ERD-nya, kamu udah sampai mana?',
            'code_language': None,
            'code_content': None,
            'attachment_name': None,
            'attachment_kind': None,
            'attachment_size': None,
            'anonymous': False,
            'created_at': now - timedelta(minutes=52),
        },
        {
            'id': uuid.uuid4(),
            'channel_id': 'general',
            'parent_id': None,
            'author_id': None,
            'author_name': 'Budi Santoso',
            'author_avatar': 'https://i.pravatar.cc/64?img=12',
            'body': 'Nih aku share draft skemanya ya.',
            'code_language': None,
            'code_content': None,
            'attachment_name': 'skema-db.pdf',
            'attachment_kind': 'file',
            'attachment_size': '820 KB',
            'anonymous': False,
            'created_at': now - timedelta(minutes=48),
        },
        {
            'id': f1_id,
            'channel_id': 'frontend',
            'parent_id': None,
            'author_id': None,
            'author_name': 'Rangga Pratama',
            'author_avatar': 'https://i.pravatar.cc/64?img=13',
            'body': 'Ini cara convert design token ke CSS variables:',
            'code_language': 'css',
            'code_content': ':root {\n  --color-primary: #e5e5e5;\n  --color-ink: #282520;\n}',
            'attachment_name': None,
            'attachment_kind': None,
            'attachment_size': None,
            'anonymous': False,
            'created_at': now - timedelta(minutes=40),
        },
        {
            'id': uuid.uuid4(),
            'channel_id': 'frontend',
            'parent_id': f1_id,
            'author_id': None,
            'author_name': 'Nadia Putri',
            'author_avatar': 'https://i.pravatar.cc/64?img=45',
            'body': 'Mantap, makasih! Langsung kupakai.',
            'code_language': None,
            'code_content': None,
            'attachment_name': None,
            'attachment_kind': None,
            'attachment_size': None,
            'anonymous': False,
            'created_at': now - timedelta(minutes=38),
        },
    ])

    # 12. DEMO USERS (Faculty & Students)
    users_table = sa.table(
        'users',
        sa.column('id', sa.UUID),
        sa.column('email', sa.Text),
        sa.column('password_hash', sa.Text),
        sa.column('role', sa.Enum('student', 'faculty', name='user_role')),
        sa.column('name', sa.Text),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    profiles_table = sa.table(
        'profiles',
        sa.column('user_id', sa.UUID),
        sa.column('avatar_url', sa.Text),
        sa.column('username', sa.Text),
        sa.column('university', sa.Text),
        sa.column('batch', sa.Integer),
        sa.column('role_title', sa.Text),
        sa.column('role_emoji', sa.Text),
        sa.column('bio', sa.Text),
        sa.column('location', sa.Text),
        sa.column('github_connected', sa.Boolean),
        sa.column('github_username', sa.Text),
        sa.column('cv_file_name', sa.Text),
        sa.column('cv_uploaded_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    user_pref_table = sa.table(
        'user_preferences',
        sa.column('user_id', sa.UUID),
        sa.column('role_id', sa.Text),
        sa.column('role_title', sa.Text),
        sa.column('role_emoji', sa.Text),
        sa.column('role_scores', postgresql.JSONB),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    github_stats_table = sa.table(
        'github_stats',
        sa.column('user_id', sa.UUID),
        sa.column('username', sa.Text),
        sa.column('total_commits', sa.Integer),
        sa.column('current_streak', sa.Integer),
        sa.column('longest_streak', sa.Integer),
        sa.column('public_repos', sa.Integer),
        sa.column('top_languages', postgresql.JSONB),
        sa.column('weeks', postgresql.JSONB),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    submissions_table = sa.table(
        'submissions',
        sa.column('id', sa.UUID),
        sa.column('user_id', sa.UUID),
        sa.column('roadmap_id', sa.Text),
        sa.column('node_key', sa.Text),
        sa.column('done', sa.Boolean),
        sa.column('file_name', sa.Text),
        sa.column('text_answer', sa.Text),
        sa.column('score', sa.Integer),
        sa.column('quiz_answers', postgresql.JSONB),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )

    # Faculty
    fac_id = uuid.uuid4()
    op.bulk_insert(users_table, [
        {
            'id': fac_id,
            'email': 'seed-faculty@sepaham.local',
            'password_hash': pw_faculty,
            'role': 'faculty',
            'name': 'Seed Faculty',
            'created_at': now,
            'updated_at': now,
        },
    ])
    op.bulk_insert(profiles_table, [
        {
            'user_id': fac_id,
            'avatar_url': 'https://i.pravatar.cc/80?img=60',
            'username': 'faculty',
            'university': 'Institut Teknologi Bandung',
            'batch': 2018,
            'role_title': 'Dosen Pembimbing',
            'role_emoji': '',
            'bio': 'Faculty supervisor at Sepaham.',
            'location': 'Bandung, Indonesia',
            'github_connected': False,
            'github_username': None,
            'cv_file_name': None,
            'cv_uploaded_at': None,
            'updated_at': now,
        }
    ])

    # Students (from frontend mock students)
    students_data = [
        {
            'name': 'Siti Rahma',
            'email': 'siti@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=5',
            'role_title': 'Frontend',
            'role_id': 'frontend-engineer',
            'roadmap_id': 'frontend',
            'cv': 'SitiRahma-CV.pdf',
            'cv_date': now - timedelta(days=40),
            'repos': 14,
            'commits': 620,
            'top_langs': [{'name': 'TypeScript', 'percentage': 60, 'color': '#3178c6'}, {'name': 'CSS', 'percentage': 25, 'color': '#563d7c'}, {'name': 'JavaScript', 'percentage': 15, 'color': '#f1e05a'}],
            'completed_nodes': ['html-css', 'javascript', 'git', 'typescript', 'tailwind', 'react', 'state-mgmt', 'nextjs'],
        },
        {
            'name': 'Budi Santoso',
            'email': 'budi@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=12',
            'role_title': 'Backend',
            'role_id': 'backend-engineer',
            'roadmap_id': 'backend',
            'cv': 'BudiSantoso-Resume.pdf',
            'cv_date': now - timedelta(days=35),
            'repos': 9,
            'commits': 410,
            'top_langs': [{'name': 'Go', 'percentage': 50, 'color': '#00ADD8'}, {'name': 'SQL', 'percentage': 30, 'color': '#e38c00'}, {'name': 'Python', 'percentage': 20, 'color': '#3572A5'}],
            'completed_nodes': ['bahasa', 'rest-api', 'database', 'auth'],
        },
        {
            'name': 'Nadia Putri',
            'email': 'nadia@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=45',
            'role_title': 'UI/UX',
            'role_id': 'frontend-engineer',
            'roadmap_id': 'frontend',
            'cv': None,
            'cv_date': None,
            'repos': 3,
            'commits': 90,
            'top_langs': [{'name': 'JavaScript', 'percentage': 100, 'color': '#f1e05a'}],
            'completed_nodes': ['html-css', 'javascript'],
        },
        {
            'name': 'Rian Hidayat',
            'email': 'rian@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=15',
            'role_title': 'Mobile',
            'role_id': 'mobile-developer',
            'roadmap_id': 'mobile',
            'cv': 'Rian-CV-2026.pdf',
            'cv_date': now - timedelta(days=48),
            'repos': 11,
            'commits': 350,
            'top_langs': [{'name': 'Kotlin', 'percentage': 55, 'color': '#A97BFF'}, {'name': 'Dart', 'percentage': 35, 'color': '#00B4AB'}, {'name': 'Java', 'percentage': 10, 'color': '#b07219'}],
            'completed_nodes': ['dasar', 'ui', 'state', 'api', 'native'],
        },
        {
            'name': 'Salsabila',
            'email': 'salsa@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=44',
            'role_title': 'Data/ML',
            'role_id': 'ml-engineer',
            'roadmap_id': 'data',
            'cv': None,
            'cv_date': None,
            'repos': 6,
            'commits': 210,
            'top_langs': [{'name': 'Python', 'percentage': 85, 'color': '#3572A5'}, {'name': 'Jupyter', 'percentage': 15, 'color': '#DA5B0B'}],
            'completed_nodes': ['python', 'statistik', 'pandas'],
        },
        {
            'name': 'Kevin Wijaya',
            'email': 'kevin@sepaham.local',
            'avatar': 'https://i.pravatar.cc/80?img=32',
            'role_title': 'Fullstack',
            'role_id': 'frontend-engineer',
            'roadmap_id': 'frontend',
            'cv': 'KevinWijaya.pdf',
            'cv_date': now - timedelta(days=30),
            'repos': 16,
            'commits': 780,
            'top_langs': [{'name': 'TypeScript', 'percentage': 45, 'color': '#3178c6'}, {'name': 'Go', 'percentage': 35, 'color': '#00ADD8'}, {'name': 'Python', 'percentage': 20, 'color': '#3572A5'}],
            'completed_nodes': ['html-css', 'javascript', 'git', 'typescript', 'tailwind', 'react'],
        },
    ]

    for st in students_data:
        st_id = uuid.uuid4()
        op.bulk_insert(users_table, [{
            'id': st_id,
            'email': st['email'],
            'password_hash': pw_student,
            'role': 'student',
            'name': st['name'],
            'created_at': now - timedelta(days=60),
            'updated_at': now,
        }])
        op.bulk_insert(profiles_table, [{
            'user_id': st_id,
            'avatar_url': st['avatar'],
            'username': st['email'].split('@')[0],
            'university': 'Institut Teknologi Bandung',
            'batch': 2022,
            'role_title': st['role_title'],
            'role_emoji': '',
            'bio': f"Mahasiswa {st['role_title']} di ITB.",
            'location': 'Bandung, Indonesia',
            'github_connected': True,
            'github_username': st['email'].split('@')[0],
            'cv_file_name': st['cv'],
            'cv_uploaded_at': st['cv_date'],
            'updated_at': now,
        }])
        op.bulk_insert(user_pref_table, [{
            'user_id': st_id,
            'role_id': st['role_id'],
            'role_title': st['role_title'],
            'role_emoji': '',
            'role_scores': {st['role_id']: 10},
            'created_at': now,
            'updated_at': now,
        }])
        op.bulk_insert(github_stats_table, [{
            'user_id': st_id,
            'username': st['email'].split('@')[0],
            'total_commits': st['commits'],
            'current_streak': 7,
            'longest_streak': 30,
            'public_repos': st['repos'],
            'top_languages': st['top_langs'],
            'weeks': [[0, 1, 2, 3, 4, 5, 6] for _ in range(12)],
            'updated_at': now,
        }])
        for n_key in st['completed_nodes']:
            op.bulk_insert(submissions_table, [{
                'id': uuid.uuid4(),
                'user_id': st_id,
                'roadmap_id': st['roadmap_id'],
                'node_key': n_key,
                'done': True,
                'file_name': None,
                'text_answer': 'Completed demo submission',
                'score': 100,
                'quiz_answers': None,
                'updated_at': now,
            }])


def downgrade() -> None:
    op.execute("DELETE FROM submissions;")
    op.execute("DELETE FROM github_stats;")
    op.execute("DELETE FROM user_preferences;")
    op.execute("DELETE FROM profiles;")
    op.execute("DELETE FROM users;")
    op.execute("DELETE FROM messages;")
    op.execute("DELETE FROM collab_applicants;")
    op.execute("DELETE FROM collab_requests;")
    op.execute("DELETE FROM lofi_tracks;")
    op.execute("DELETE FROM ai_internships;")
    op.execute("DELETE FROM dev_quotes;")
    op.execute("DELETE FROM internship_contacts;")
    op.execute("DELETE FROM roadmap_edges;")
    op.execute("DELETE FROM roadmap_nodes;")
    op.execute("DELETE FROM roadmaps;")
    op.execute("DELETE FROM channels;")
    op.execute("DELETE FROM servers;")
    op.execute("DELETE FROM badges;")
    op.execute("DELETE FROM onboarding_questions;")
    op.execute("DELETE FROM hobbies;")
    op.execute("DELETE FROM roles;")

